/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://wcotmkvaxjf27k3tm5vcxmj6he.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jr7afj6yi5gsrcdn2c6ocsdks4",
    "aws_cognito_identity_pool_id": "us-east-2:33534cd6-6f8a-422a-8eb8-f7bdca4621c7",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ej9fad0Oc",
    "aws_user_pools_web_client_id": "4mjhauq40i74uo997nsj99hjls",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "firstwebapp-storage59d46-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
